In [1]:
from types_data.utils import RasterIOInd
import geopandas as gpd, warnings
warnings.filterwarnings('ignore')



decision = "../Data/Raster/ETH_Maternal_and_child_socioeconomic/ETH_DECISION_MEAN.tif"
hwealth = "../Data/Raster/ETH_Maternal_and_child_socioeconomic/ETH_HWEALTH_MEAN.tif"
education = "../Data/Raster/ETH_Maternal_and_child_socioeconomic/ETH_MEDUCATION_MEAN.tif"
dist_data = gpd.read_file("../Data/gjson/adm_3.geojson").sort_values('area')

In [2]:
desc = RasterIOInd(
    decision,
    dist_data,
    "decision",
    "../output/maternal_child_socioeconomic/decision.csv",
    only_metric=True,
)
desc.get_result()
# print(osm.total_time)
desc.result_df.head()

100%|██████████| 1141/1141 [00:09<00:00, 114.43it/s]

,id,fnid,parent_id,admin_0,admin_1,admin_2,admin_3,decision_mean,decision_sd,decision_sum
881,223677,ET2023A3150112,222765,Ethiopia,Dire Dawa,Dire Dawa urban,Hafat Issa,0.237841,0.000000,0.237841
929,223725,ET2023A3170805,222768,Ethiopia,South West Ethiopia,Sheka,Masha town,0.321509,0.000000,0.321509
1054,223850,ET2023A3181511,222779,Ethiopia,South Ethiopia,Gofa,Laha town,0.323522,0.001806,0.647045
51,222847,ET2023A3010315,222697,Ethiopia,Tigray,East Tigray,Atsbi town,0.217190,0.000000,0.217190
879,223675,ET2023A3150110,222765,Ethiopia,Dire Dawa,Dire Dawa urban,Gende Kore,0.236762,0.000000,0.236762

In [3]:
hw = RasterIOInd(
    hwealth,
    dist_data,
    "hwealth",
    "../output/maternal_child_socioeconomic/hwealth.csv",
    only_metric=True,
)
hw.get_result()
# print(osm.total_time)
hw.result_df.head()

  0%|          | 0/1141 [00:00<?, ?it/s]

100%|██████████| 1141/1141 [00:12<00:00, 93.33it/s]

,id,fnid,parent_id,admin_0,admin_1,admin_2,admin_3,hwealth_mean,hwealth_sd,hwealth_sum
881,223677,ET2023A3150112,222765,Ethiopia,Dire Dawa,Dire Dawa urban,Hafat Issa,0.000480,0.000000,0.000480
929,223725,ET2023A3170805,222768,Ethiopia,South West Ethiopia,Sheka,Masha town,0.191217,0.000000,0.191217
1054,223850,ET2023A3181511,222779,Ethiopia,South Ethiopia,Gofa,Laha town,0.197512,0.015824,0.395024
51,222847,ET2023A3010315,222697,Ethiopia,Tigray,East Tigray,Atsbi town,0.293674,0.000000,0.293674
879,223675,ET2023A3150110,222765,Ethiopia,Dire Dawa,Dire Dawa urban,Gende Kore,0.000087,0.000000,0.000087

In [4]:
edu = RasterIOInd(
    education,
    dist_data,
    "education",
    "../output/maternal_child_socioeconomic/education.csv",
    only_metric=True,
)
edu.get_result()
# print(osm.total_time)
edu.result_df.head()

100%|██████████| 1141/1141 [00:11<00:00, 97.20it/s]

,id,fnid,parent_id,admin_0,admin_1,admin_2,admin_3,education_mean,education_sd,education_sum
881,223677,ET2023A3150112,222765,Ethiopia,Dire Dawa,Dire Dawa urban,Hafat Issa,0.192627,0.000000,0.192627
929,223725,ET2023A3170805,222768,Ethiopia,South West Ethiopia,Sheka,Masha town,0.403521,0.000000,0.403521
1054,223850,ET2023A3181511,222779,Ethiopia,South Ethiopia,Gofa,Laha town,0.555236,0.001554,1.110471
51,222847,ET2023A3010315,222697,Ethiopia,Tigray,East Tigray,Atsbi town,0.561991,0.000000,0.561991
879,223675,ET2023A3150110,222765,Ethiopia,Dire Dawa,Dire Dawa urban,Gende Kore,0.162838,0.000000,0.162838